// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:lukhu_packages_pkg/lukhu_packages_pkg.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_app_id_file.json';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOJ3pRT4lxrKPhY65msAVnS25-dd4nhtk',
    appId: '1:1048850599976:web:fde426a66a08551f79251d',
    messagingSenderId: '1048850599976',
    projectId: 'lukhu-app',
    authDomain: 'lukhu-app.firebaseapp.com',
    storageBucket: 'lukhu-app.appspot.com',
    measurementId: 'G-PE2WT94ZYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo56KzAgOqbjFw9jO2XpJxwh1XT423dxg',
    appId: '1:1048850599976:android:c169519e60ae0d4079251d',
    messagingSenderId: '1048850599976',
    projectId: 'lukhu-app',
    storageBucket: 'lukhu-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6LTJcYVYVcq_Jo9aC-Ct6hVJ0sZNkw8A',
    appId: '1:1048850599976:ios:29576dc9b422bc9279251d',
    messagingSenderId: '1048850599976',
    projectId: 'lukhu-app',
    storageBucket: 'lukhu-app.appspot.com',
    iosClientId: '1048850599976-d2s6pk8c02c9i66fofp237hft0gdeb5a.apps.googleusercontent.com',
    iosBundleId: 'com.lukhu.mobile.app',
  );
}
